# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path prepended to sys.path of env.py
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to copy to slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded relative to the
# directory containing the alembic.ini file
# make_imports_relative = false

version_locations = %(here)s/alembic/versions

# version path separator; defaults to 'os.pathsep'
# version_path_separator = :

# set to 'true' to search for newer versions in target database
# recursive_version_lookup = false

# set to 'true' to search for missing versions in target database
# search_for_versions = false


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# after generating new migration scripts.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
